<?php

$dgs_agencies = array(

	'generated' =>  date( 'Y-m-d H:i:s' ),
	'api_version' => 1,
	'agencies' => array(
		new DGS_Agency( 'Administrative Conference of the United States (ACUS)', 'acus', 'www.acus.gov' ),
		new DGS_Agency( 'Advisory Council on Historic Preservation (ACHP)', 'achp', 'www.achp.gov' ),
		new DGS_Agency( 'African Development Foundation (ADF)', 'adf', 'www.adf.gov' ),
		new DGS_Agency( 'United States Agency for International Development (USAID)', 'usaid', 'www.usaid.gov' ),
		new DGS_Agency( 'Department of Agriculture (USDA)', 'usda', 'www.usda.gov' ),
		new DGS_Agency( 'AMTRAK (National Railroad Passenger Corporation)', 'amtrak', 'www.amtrak.com' ),
		new DGS_Agency( 'Broadcasting Board of Governors, International Broadcasting Bureau (BBG)', 'bbg', 'www.bbg.gov' ),
		new DGS_Agency( 'Central Intelligence Agency (CIA)', 'cia', 'www.cia.gov' ),
		new DGS_Agency( 'Department of Commerce', 'commerce', 'www.commerce.gov' ),
		new DGS_Agency( 'Commission on Civil Rights (USCCR)', 'usccr', 'www.usccr.gov' ),
		new DGS_Agency( 'Commodity Futures Trading Commission (CFTC)', 'cftc', 'www.cftc.gov' ),
		new DGS_Agency( 'Consumer Product Safety Commission (CPSC)', 'cpsc', 'www.cpsc.gov, www.serve.gov' ),
		new DGS_Agency( 'Corporation for National and Community Service (CNCS)', 'nationalservice', 'www.nationalservice.gov' ),
		new DGS_Agency( 'Court Services and Offender Supervision Agency for the District of Columbia (CSOSA)', 'csosa', 'www.csosa.gov' ),
		new DGS_Agency( 'Defense Nuclear Facilities Safety Board (DNFSB)', 'dnfsb', 'www.dnfsb.gov' ),
		new DGS_Agency( 'Department of Defense (DOD)', 'defense', 'www.defense.gov' ),
		new DGS_Agency( 'Department of Education (ED)', 'ed', 'www.ed.gov' ),
		new DGS_Agency( 'Election Assistance Commission (EAC)', 'eac', 'www.eac.gov' ),
		new DGS_Agency( 'Department of Energy (DOE)', 'energy', 'www.energy.gov' ),
		new DGS_Agency( 'Environmental Protection Agency (EPA)', 'epa', 'www.epa.gov' ),
		new DGS_Agency( 'Equal Employment Opportunity Commission (EEOC)', 'eeoc', 'www.eeoc.gov' ),
		new DGS_Agency( 'Export-Import Bank of the United States (EXIM)', 'exim', 'www.exim.gov' ),
		new DGS_Agency( 'Farm Credit Administration (FCA)', 'fca', 'www.fca.gov' ),
		new DGS_Agency( 'Federal Communications Commission (FCC)', 'fcc', 'www.fcc.gov' ),
		new DGS_Agency( 'Federal Deposit Insurance Corporation (FDIC)', 'fdic', 'www.fdic.gov' ),
		new DGS_Agency( 'Federal Election Commission (FEC)', 'fec', 'www.fec.gov' ),
		new DGS_Agency( 'Federal Energy Regulatory Commission (FERC)', 'ferc', 'www.ferc.gov' ),
		new DGS_Agency( 'Federal Housing Finance Board (FHFA)', 'fhfa', 'www.fhfa.gov' ),
		new DGS_Agency( 'Federal Labor Relations Authority (FLRA)', 'flra', 'www.flra.gov' ),
		new DGS_Agency( 'Federal Maritime Commission (FMC)', 'fmc', 'www.fmc.gov' ),
		new DGS_Agency( 'Federal Mediation and Conciliation Service (FMCS)', 'fmcs', 'www.fmcs.gov' ),
		new DGS_Agency( 'Federal Mine Safety and Health Review Commission (FMSHRC)', 'fmshrc', 'www.fmshrc.gov' ),
		new DGS_Agency( 'Federal Reserve System', 'federalreserve', 'www.federalreserve.gov' ),
		new DGS_Agency( 'Federal Retirement Thrift Investment Board (FRTIB)', 'frtib', 'www.frtib.gov' ),
		new DGS_Agency( 'Federal Trade Commission (FTC)', 'ftc', 'www.ftc.gov' ),
		new DGS_Agency( 'General Services Administration (GSA)', 'gsa', 'www.gsa.gov' ),
		new DGS_Agency( 'Department of Health and Human Services (HHS)', 'hhs', 'www.hhs.gov' ),
		new DGS_Agency( 'Department of Homeland Security (DHS)', 'dhs', 'www.dhs.gov' ),
		new DGS_Agency( 'Department of Housing and Urban Development (HUD)', 'hud', 'www.hud.gov' ),
		new DGS_Agency( 'Institute of Museum and Library Services (IMLS)', 'imls', 'www.imls.gov' ),
		new DGS_Agency( 'Inter-American Foundation (IAF)', 'iaf', 'www.iaf.gov' ),
		new DGS_Agency( 'Department of the Interior (DOI)', 'doi', 'www.doi.gov' ),
		new DGS_Agency( 'United States International Trade Commission (USITC)', 'usitc', 'www.usitc.gov' ),
		new DGS_Agency( 'Department of Justice (DOJ)', 'justice', 'www.justice.gov' ),
		new DGS_Agency( 'Department of Labor (DOL)', 'labor', 'www.labor.gov' ),
		new DGS_Agency( 'Merit Systems Protection Board (MSPB)', 'mspb', 'www.mspb.gov' ),
		new DGS_Agency( 'Millennium Challenge Corporation (MCC)', 'mcc', 'www.mcc.gov' ),
		new DGS_Agency( 'National Aeronautics and Space Administration (NASA)', 'nasa', 'www.nasa.gov' ),
		new DGS_Agency( 'National Archives and Records Administration (NARA)', 'archives', 'www.archives.gov' ),
		new DGS_Agency( 'National Capital Planning Commission (NCPC)', 'ncpc', 'www.ncpc.gov' ),
		new DGS_Agency( 'National Council on Disability (NCD)', 'ncd', 'www.ncd.gov' ),
		new DGS_Agency( 'National Credit Union Administration (NCUA)', 'ncua', 'www.ncua.gov' ),
		new DGS_Agency( 'National Endowment for the Arts (NEA)', 'nea', 'www.nea.gov' ),
		new DGS_Agency( 'National Endowment for the Humanities (NEH)', 'neh', 'www.neh.gov' ),
		new DGS_Agency( 'National Labor Relations Board (NLRB)', 'nlrb', 'www.nlrb.gov' ),
		new DGS_Agency( 'National Mediation Board (NMB)', 'nmb', 'www.nmb.gov' ),
		new DGS_Agency( 'National Science Foundation (NSF)', 'nsf', 'www.nsf.gov' ),
		new DGS_Agency( 'National Transportation Safety Board (NTSB)', 'ntsb', 'www.ntsb.gov' ),
		new DGS_Agency( 'Nuclear Regulatory Commission (NRC)', 'nrc', 'www.nrc.gov' ),
		new DGS_Agency( 'Occupational Safety and Health Review Commission (OSHRC)', 'oshrc', 'www.oshrc.gov' ),
		new DGS_Agency( 'Office of Compliance', 'compliance', 'www.compliance.gov' ),
		new DGS_Agency( 'Office of Government Ethics (USOGE)', 'usoge', 'www.usoge.gov' ),
		new DGS_Agency( 'Office of Personnel Management (OPM)', 'opm', 'www.opm.gov' ),
		new DGS_Agency( 'Office of Special Counsel (OSC)', 'osc', 'www.osc.gov' ),
		new DGS_Agency( 'Office of the Director of National Intelligence (DNI)', 'dni', 'www.dni.gov' ),
		new DGS_Agency( 'Office of the National Counterintelligence Executive (NCIX)', 'ncix', 'www.ncix.gov' ),
		new DGS_Agency( 'Overseas Private Investment Corporation (OPIC)', 'opic', 'www.opic.gov' ),
		new DGS_Agency( 'Peace Corps', 'peacecorps', 'www.peacecorps.gov' ),
		new DGS_Agency( 'Pension Benefit Guaranty Corporation (PBGC)', 'pbgc', 'www.pbgc.gov' ),
		new DGS_Agency( 'Postal Regulatory Commission (PRC)', 'prc', 'www.prc.gov' ),
		new DGS_Agency( 'United States Postal Service (USPS)', 'usps', 'www.usps.com' ),
		new DGS_Agency( 'Railroad Retirement Board (RRB)', 'rrb', 'www.rrb.gov' ),
		new DGS_Agency( 'Securities and Exchange Commission (SEC)', 'sec', 'www.sec.gov' ),
		new DGS_Agency( 'Selective Service System (SSS)', 'sss', 'www.sss.gov' ),
		new DGS_Agency( 'Small Business Administration (SBA)', 'sba', 'www.sba.gov' ),
		new DGS_Agency( 'Social Security Administration (SSA)', 'ssa', 'www.ssa.gov' ),
		new DGS_Agency( 'Department of State', 'state', 'www.state.gov' ),
		new DGS_Agency( 'Tennessee Valley Authority (TVA)', 'tva', 'www.tva.gov' ),
		new DGS_Agency( 'U.S. Trade and Development Agency (USTDA)', 'ustda', 'www.ustda.gov' ),
		new DGS_Agency( 'Department of Transportation (DOT)', 'dot', 'www.dot.gov' ),
		new DGS_Agency( 'Department of the Treasury', 'treasury', 'www.treasury.gov' ),
		new DGS_Agency( 'Department of Veterans Affairs (VA)', 'va', 'www.va.gov' ),
		new DGS_Agency( 'Executive Office of the President (EOP)', 'eop', 'www.whitehouse.gov' ),
		new DGS_Agency( 'Supreme Court (SCOTUS)', 'supremecourt', 'www.supremecourt.gov' ),
		new DGS_Agency( 'House of Representatives', 'house', 'www.house.gov' ),
		new DGS_Agency( 'U.S. Senate', 'senate', 'www.senate.gov' ),
		new DGS_Agency( 'Library of Congress (LOC)', 'loc', 'www.libraryofcongress.gov' ),
		new DGS_Agency( 'U.S. Court of Appeals (CAFC)', 'courtofappeals', 'www.cafc.uscourts.gov' ),
		new DGS_Agency( 'U.S. District Courts', 'districtcourts', 'www.uscourts.gov/FederalCourts/UnderstandingtheFederalCourts/DistrictCourts.aspx' ),
		new DGS_Agency( 'U.S. Bankruptcy Courts', 'backruptcycourts', 'www.uscourts.gov/FederalCourts/UnderstandingtheFederalCourts/BankruptcyCourts.aspx' ),
		new DGS_Agency( 'U.S. Court of Appeals for the Armed Forces', 'courtofappealsforarmedforces', 'www.armfor.uscourts.gov' ),
		new DGS_Agency( 'U.S. Court of Federal Claims (USCFC)', 'courtoffederalclaims', 'www.uscfc.uscourts.gov' ),
		new DGS_Agency( 'U.S. Court of International Trade', 'courtofinternationaltrade', 'www.cit.uscourts.gov' ),
		new DGS_Agency( 'U.S. Tax Court', 'ustaxcourt', 'www.ustaxcourt.gov' ),
		new DGS_Agency( 'U.S. Court of Appeals for Veterans Claims (CAVC)', 'courtofappealsforveterans', 'www.uscourts.cavc.gov' ),
		new DGS_Agency( 'Judicial Panel on Multidistrict Litigation (JPML)', 'jpml', 'www.jpml.uscourts.gov' ),
		new DGS_Agency( 'Administrative Office of the U.S. Courts', 'uscourts', 'www.uscourts.gov' ),
		new DGS_Agency( 'Federal Judicial Center (FJC)', 'fjc', 'www.fjc.gov' ),
		new DGS_Agency( 'U.S. Sentencing Commission (USSC)', 'ussc', 'www.ussc.gov' ),
		new DGS_Agency( 'Architect of the Capitol (AOC)', 'capitol', 'www.aoc.gov' ),
		new DGS_Agency( 'United States Botanic Garden', 'botanicgarden', 'www.usbg.gov' ),
		new DGS_Agency( 'Government Accountability Office (GAO)', 'gao', 'www.gao.gov' ),
		new DGS_Agency( 'Government Printing Office (GPO)', 'gpo', 'www.gpo.gov' ),
		new DGS_Agency( 'Congressional Budget Office (CBO)', 'cbo', 'www.cbo.gov' ),
		new DGS_Agency( 'Information Sharing Environment (ISE)', 'ise', 'ise.gov' ),
		new DGS_Agency( 'Panama Canal Authority (ACP)', 'acp', 'www.pancanal.com' ),
		new DGS_Agency( 'Internal Revenue Service (IRS)', 'irs', 'irs.gov' ),
		new DGS_Agency( 'U.S. Energy Information Administration (EIA)', 'eia', 'www.eia.gov' ),
	),

);
